# Constants specific to the google search project

SEARCH_KEY = 'SEARCH_KEY'
SEARCH_RESULT_STRING = 'SEARCH_RESULT'
SEARCH_RESULT_TITLES = 'SEARCH_RESULT_TITLES'
SEARCH_RESULT_TITLES_LIST = 'SEARCH_RESULT_TITLES_LIST'